port: 3000
highlighter: null
lsi: false
permalink: /:year/:month/:day/:title.html
# paginate: 50
markdown: rdiscount
# enables SmartyPants (nice curly quotation marks, em/en dashes, elipses, etc):
rdiscount:
  extensions: [smart]


# Since GH pages override this to "true", we test this value to see if we are running locally
safe: false
include: [".well-known"]


# The Reveal theme
reveal_theme: black.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/ 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal.js/

# Don't change anything below
markdown: redcarpet
pygments: true
markdown_ext: ignoreme

